### ISSUE TITLE
Multiple Python 3.10+ issues

### ISSUE THREAD

**Issue by clach04** [jmathai/elodie#418]
1. Pillow 8.0.0 does not support Python 3.10
    a. does not provide prebuilt Windows binaries
2. tabulate (0.7.7) latest version as of 2022-11-12 does not support Python >=3.10 
3. SyntaxWarning: "is" with a literal.

## Pillow

    C:\Users\clach04\AppData\Local\Temp\pip-install-i85cqwbb\pillow_86813ad0d0c649aabea19ecf8728fa8d\setup.py:41: RuntimeWarning: Pillow 8.0.0 does not support
    Python 3.10 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.

workaround:

    pip install pillow  # or edit requirements.txt

pillow-9.3.0 installs fine

### import error

    (py310venv) C:\code\py\elodie>python elodie.py
    Traceback (most recent call last):
      File "C:\code\py\elodie\elodie.py", line 32, in <module>
        from elodie.result import Result
      File "C:\code\py\elodie\elodie\result.py", line 1, in <module>
        from tabulate import tabulate
      File "C:\py310venv\lib\site-packages\tabulate.py", line 7, in <module>
        from collections import namedtuple, Iterable
    ImportError: cannot import name 'Iterable' from 'collections' (C:\Pythons\Python310\lib\collections\__init__.py)

Hack to tabulate

    #from collections import namedtuple, Iterable
    from collections import namedtuple
    try:
        from collections import Iterable
    except ImportError:
        from collections.abc import Iterable

### syntax warning

    (py310venv) C:\code\py\elodie>python elodie.py
    C:\py310venv\lib\site-packages\tabulate.py:201: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if isinstance(val, (_text_type, _binary_type)) and val.strip() is "":
    Usage: elodie.py [OPTIONS] COMMAND [ARGS]...

    Options:
      --help  Show this message and exit.

    Commands:
      batch        Run batch() for all plugins.
      generate-db  Regenerate the hash.json database which...
      import       Import files or directories by reading their...
      update       Update a file's EXIF.
      verify

2nd hack:

        #if isinstance(val, (_text_type, _binary_type)) and val.strip() is "":
        if isinstance(val, (_text_type, _binary_type)) and val.strip() == "":

**Comment by clach04** [comment]
Looks like upstream tabulate already fixed python > 3.9 issue(s)

https://github.com/astanin/python-tabulate/blob/83fd4fb98926c8a6fdf45caa1b91ee8913b64dcb/tabulate/__init__.py#L4

**Comment by clach04** [comment]
diff --git a/requirements.txt b/requirements.txt
    index 33f5dbb..8484b21 100644
    --- a/requirements.txt
    +++ b/requirements.txt
    @@ -5,5 +5,6 @@ future==0.16.0
     configparser==3.5.0
     tabulate==0.7.7
     Pillow==6.2.2; python_version == '2.7'
    -Pillow==8.0; python_version >= '3.6'
    +#Pillow==8.0; python_version >= '3.6'
    +Pillow==9.3.0; python_version >= '3.6'
     six==1.9

**Comment by jmathai** [comment]
I'll fix this once I get the tests updated to work with the new MapQuest API (gh-421).

**Comment by jmathai** [comment]
Nose (the testing framework used for this project) does not support python 3.10. Fixing these errors and passing tests looks like it requires a larger effort of moving to pytest or similar.

**Comment by gilles6** [comment]
What workaround can/should we use on macos ?

**Comment by jmathai** [comment]
You can [download python 3.9](https://www.python.org/downloads/macos/) for OSX or use [homebrew](https://formulae.brew.sh/formula/python@3.9).

**Comment by clach04** [comment]
> Nose (the testing framework used for this project) does not support python 3.10. Fixing these errors and passing tests looks like it requires a larger effort of moving to pytest or similar.

yikes, just checked into this, options appear to be:

1. try version in github (not pypi version) https://github.com/nose-devs/nose/issues/1118 suggests this is worth trying, i.e. pip install with a git url
2. move to nose2 https://github.com/nose-devs/nose2 .... which apparently/might requires changing tests, nose (v1) is apparently no longer maintained which is not clear from https://github.com/nose-devs/nose
3. move to pytest -- which seems the most practical as a stable target.

It maybe that number 2 is less work but I don't have a good feeling about it (and no hard facts).

refs:

* https://github.com/nose-devs/nose/issues/1122
* https://github.com/nose-devs/nose/issues/1118
* https://github.com/nose-devs/nose/issues/1099

I'm still using unittest/unittest2 for my personal projects but the other runners have much nicer run options.

**Comment by gilles6** [comment]
@jmathai Thanks
I'm getting the following error when using python 3.9:
```
python3.9 ~/elodie/elodie.py
Traceback (most recent call last):
  File "/Users/me/elodie/elodie.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by jmathai** [comment]
@gilles6 Did you run `pip install -r requirements.txt`?

**Comment by gilles6** [comment]
@jmathai Yes, I did
```
~/elodie master $ pip install -r requirements.txt
Ignoring Pillow: markers 'python_version == "2.7"' don't match your environment
Requirement already satisfied: click==6.6 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (6.6)
Requirement already satisfied: requests==2.20.0 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.20.0)
Requirement already satisfied: Send2Trash==1.3.0 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: future==0.16.0 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: configparser==3.5.0 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (3.5.0)
Requirement already satisfied: tabulate==0.7.7 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.7.7)
Requirement already satisfied: Pillow==9.3 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (9.3.0)
Requirement already satisfied: six==1.9 in /usr/local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.9.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/site-packages (from requests==2.20.0->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests==2.20.0->-r requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests==2.20.0->-r requirements.txt (line 2)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests==2.20.0->-r requirements.txt (line 2)) (1.24.3)
$ cd ~/Pictures/test
$ python3.9 ~/elodie/elodie.py input output
Traceback (most recent call last):
  File "/Users/gvigner/elodie/elodie.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by jmathai** [comment]
Your `pip install -r requirements.txt` is installing the packages for python 3.10. You can see this in the path which is being referenced (`Requirement already satisfied: click==6.6 in /usr/local/lib/python3.10/site-packages`).

Try this instead. `python3.9 -m pip install -r requirements.txt`

**Comment by patsevanton** [comment]
Same issue on Python 3.10
```
Traceback (most recent call last):
  File "/home/user/IdeaProjects/elodie/./elodie.py", line 32, in <module>
    from elodie.result import Result
  File "/home/user/IdeaProjects/elodie/elodie/result.py", line 1, in <module>
    from tabulate import tabulate
  File "/home/user/IdeaProjects/elodie/venv/lib/python3.10/site-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by webysther** [comment]
How to fix working with python 3.9 on ubuntu:

```sh
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.9
sudo apt install python3.9-distutils
python3.9 -m pip install -r requirements.txt
python3.9 ./elodie.py import --help
```

**Comment by webysther** [comment]
> Is there a workaround for this in Debian Bookworm?

Using [uv](https://docs.astral.sh/uv) with [poe](https://github.com/nat-n/poethepoet) get the work done
